.TH "" "" "" "" ""
.SH vz\-train
.RS
.PP
No name given yet
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ vz\-train
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ vz\-train
\ \ \ \ vz\-train\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ vz\-train

Commands:

Arguments:
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH New features
.IP \[bu] 2
initial requests working \-\- Apr 10th
16 (../../commit/33079fd61783bececfff79dbea01cbe542d0e709)
.IP \[bu] 2
initial commit \-\- Apr 10th
16 (../../commit/7bfe786b7ed5a2852cc447d711cce7203700584c)
